package com.example.demo.bean.mybatis;

import java.util.ArrayList;
import java.util.List;

public class MGenderExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public MGenderExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andNameJpnIsNull() {
			addCriterion("name_jpn is null");
			return (Criteria) this;
		}

		public Criteria andNameJpnIsNotNull() {
			addCriterion("name_jpn is not null");
			return (Criteria) this;
		}

		public Criteria andNameJpnEqualTo(String value) {
			addCriterion("name_jpn =", value, "nameJpn");
			return (Criteria) this;
		}

		public Criteria andNameJpnNotEqualTo(String value) {
			addCriterion("name_jpn <>", value, "nameJpn");
			return (Criteria) this;
		}

		public Criteria andNameJpnGreaterThan(String value) {
			addCriterion("name_jpn >", value, "nameJpn");
			return (Criteria) this;
		}

		public Criteria andNameJpnGreaterThanOrEqualTo(String value) {
			addCriterion("name_jpn >=", value, "nameJpn");
			return (Criteria) this;
		}

		public Criteria andNameJpnLessThan(String value) {
			addCriterion("name_jpn <", value, "nameJpn");
			return (Criteria) this;
		}

		public Criteria andNameJpnLessThanOrEqualTo(String value) {
			addCriterion("name_jpn <=", value, "nameJpn");
			return (Criteria) this;
		}

		public Criteria andNameJpnLike(String value) {
			addCriterion("name_jpn like", value, "nameJpn");
			return (Criteria) this;
		}

		public Criteria andNameJpnNotLike(String value) {
			addCriterion("name_jpn not like", value, "nameJpn");
			return (Criteria) this;
		}

		public Criteria andNameJpnIn(List<String> values) {
			addCriterion("name_jpn in", values, "nameJpn");
			return (Criteria) this;
		}

		public Criteria andNameJpnNotIn(List<String> values) {
			addCriterion("name_jpn not in", values, "nameJpn");
			return (Criteria) this;
		}

		public Criteria andNameJpnBetween(String value1, String value2) {
			addCriterion("name_jpn between", value1, value2, "nameJpn");
			return (Criteria) this;
		}

		public Criteria andNameJpnNotBetween(String value1, String value2) {
			addCriterion("name_jpn not between", value1, value2, "nameJpn");
			return (Criteria) this;
		}

		public Criteria andRecordIdIsNull() {
			addCriterion("record_id is null");
			return (Criteria) this;
		}

		public Criteria andRecordIdIsNotNull() {
			addCriterion("record_id is not null");
			return (Criteria) this;
		}

		public Criteria andRecordIdEqualTo(Long value) {
			addCriterion("record_id =", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotEqualTo(Long value) {
			addCriterion("record_id <>", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdGreaterThan(Long value) {
			addCriterion("record_id >", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdGreaterThanOrEqualTo(Long value) {
			addCriterion("record_id >=", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdLessThan(Long value) {
			addCriterion("record_id <", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdLessThanOrEqualTo(Long value) {
			addCriterion("record_id <=", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdIn(List<Long> values) {
			addCriterion("record_id in", values, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotIn(List<Long> values) {
			addCriterion("record_id not in", values, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdBetween(Long value1, Long value2) {
			addCriterion("record_id between", value1, value2, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotBetween(Long value1, Long value2) {
			addCriterion("record_id not between", value1, value2, "recordId");
			return (Criteria) this;
		}

		public Criteria andNameJpnHiraIsNull() {
			addCriterion("name_jpn_hira is null");
			return (Criteria) this;
		}

		public Criteria andNameJpnHiraIsNotNull() {
			addCriterion("name_jpn_hira is not null");
			return (Criteria) this;
		}

		public Criteria andNameJpnHiraEqualTo(String value) {
			addCriterion("name_jpn_hira =", value, "nameJpnHira");
			return (Criteria) this;
		}

		public Criteria andNameJpnHiraNotEqualTo(String value) {
			addCriterion("name_jpn_hira <>", value, "nameJpnHira");
			return (Criteria) this;
		}

		public Criteria andNameJpnHiraGreaterThan(String value) {
			addCriterion("name_jpn_hira >", value, "nameJpnHira");
			return (Criteria) this;
		}

		public Criteria andNameJpnHiraGreaterThanOrEqualTo(String value) {
			addCriterion("name_jpn_hira >=", value, "nameJpnHira");
			return (Criteria) this;
		}

		public Criteria andNameJpnHiraLessThan(String value) {
			addCriterion("name_jpn_hira <", value, "nameJpnHira");
			return (Criteria) this;
		}

		public Criteria andNameJpnHiraLessThanOrEqualTo(String value) {
			addCriterion("name_jpn_hira <=", value, "nameJpnHira");
			return (Criteria) this;
		}

		public Criteria andNameJpnHiraLike(String value) {
			addCriterion("name_jpn_hira like", value, "nameJpnHira");
			return (Criteria) this;
		}

		public Criteria andNameJpnHiraNotLike(String value) {
			addCriterion("name_jpn_hira not like", value, "nameJpnHira");
			return (Criteria) this;
		}

		public Criteria andNameJpnHiraIn(List<String> values) {
			addCriterion("name_jpn_hira in", values, "nameJpnHira");
			return (Criteria) this;
		}

		public Criteria andNameJpnHiraNotIn(List<String> values) {
			addCriterion("name_jpn_hira not in", values, "nameJpnHira");
			return (Criteria) this;
		}

		public Criteria andNameJpnHiraBetween(String value1, String value2) {
			addCriterion("name_jpn_hira between", value1, value2, "nameJpnHira");
			return (Criteria) this;
		}

		public Criteria andNameJpnHiraNotBetween(String value1, String value2) {
			addCriterion("name_jpn_hira not between", value1, value2, "nameJpnHira");
			return (Criteria) this;
		}

		public Criteria andNameUsaIsNull() {
			addCriterion("name_usa is null");
			return (Criteria) this;
		}

		public Criteria andNameUsaIsNotNull() {
			addCriterion("name_usa is not null");
			return (Criteria) this;
		}

		public Criteria andNameUsaEqualTo(String value) {
			addCriterion("name_usa =", value, "nameUsa");
			return (Criteria) this;
		}

		public Criteria andNameUsaNotEqualTo(String value) {
			addCriterion("name_usa <>", value, "nameUsa");
			return (Criteria) this;
		}

		public Criteria andNameUsaGreaterThan(String value) {
			addCriterion("name_usa >", value, "nameUsa");
			return (Criteria) this;
		}

		public Criteria andNameUsaGreaterThanOrEqualTo(String value) {
			addCriterion("name_usa >=", value, "nameUsa");
			return (Criteria) this;
		}

		public Criteria andNameUsaLessThan(String value) {
			addCriterion("name_usa <", value, "nameUsa");
			return (Criteria) this;
		}

		public Criteria andNameUsaLessThanOrEqualTo(String value) {
			addCriterion("name_usa <=", value, "nameUsa");
			return (Criteria) this;
		}

		public Criteria andNameUsaLike(String value) {
			addCriterion("name_usa like", value, "nameUsa");
			return (Criteria) this;
		}

		public Criteria andNameUsaNotLike(String value) {
			addCriterion("name_usa not like", value, "nameUsa");
			return (Criteria) this;
		}

		public Criteria andNameUsaIn(List<String> values) {
			addCriterion("name_usa in", values, "nameUsa");
			return (Criteria) this;
		}

		public Criteria andNameUsaNotIn(List<String> values) {
			addCriterion("name_usa not in", values, "nameUsa");
			return (Criteria) this;
		}

		public Criteria andNameUsaBetween(String value1, String value2) {
			addCriterion("name_usa between", value1, value2, "nameUsa");
			return (Criteria) this;
		}

		public Criteria andNameUsaNotBetween(String value1, String value2) {
			addCriterion("name_usa not between", value1, value2, "nameUsa");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.m_gender
     *
     * @mbg.generated do_not_delete_during_merge Thu Feb 13 16:41:48 JST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}