package com.example.demo.bean.mybatis;

public class MGender {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_gender.name_jpn
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	private String nameJpn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_gender.record_id
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	private Long recordId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_gender.name_jpn_hira
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	private String nameJpnHira;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_gender.name_usa
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	private String nameUsa;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_gender.name_jpn
	 * @return  the value of public.m_gender.name_jpn
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public String getNameJpn() {
		return nameJpn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_gender.name_jpn
	 * @param nameJpn  the value for public.m_gender.name_jpn
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public void setNameJpn(String nameJpn) {
		this.nameJpn = nameJpn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_gender.record_id
	 * @return  the value of public.m_gender.record_id
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public Long getRecordId() {
		return recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_gender.record_id
	 * @param recordId  the value for public.m_gender.record_id
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public void setRecordId(Long recordId) {
		this.recordId = recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_gender.name_jpn_hira
	 * @return  the value of public.m_gender.name_jpn_hira
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public String getNameJpnHira() {
		return nameJpnHira;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_gender.name_jpn_hira
	 * @param nameJpnHira  the value for public.m_gender.name_jpn_hira
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public void setNameJpnHira(String nameJpnHira) {
		this.nameJpnHira = nameJpnHira;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_gender.name_usa
	 * @return  the value of public.m_gender.name_usa
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public String getNameUsa() {
		return nameUsa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_gender.name_usa
	 * @param nameUsa  the value for public.m_gender.name_usa
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public void setNameUsa(String nameUsa) {
		this.nameUsa = nameUsa;
	}
}