package com.example.demo.bean.mybatis;

public class MPrefecture {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_prefecture.name
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_prefecture.record_id
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	private Long recordId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_prefecture.name_hira
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	private String nameHira;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_prefecture.name_kana
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	private String nameKana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_prefecture.name_roma
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	private String nameRoma;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_prefecture.name
	 * @return  the value of public.m_prefecture.name
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_prefecture.name
	 * @param name  the value for public.m_prefecture.name
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_prefecture.record_id
	 * @return  the value of public.m_prefecture.record_id
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public Long getRecordId() {
		return recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_prefecture.record_id
	 * @param recordId  the value for public.m_prefecture.record_id
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public void setRecordId(Long recordId) {
		this.recordId = recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_prefecture.name_hira
	 * @return  the value of public.m_prefecture.name_hira
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public String getNameHira() {
		return nameHira;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_prefecture.name_hira
	 * @param nameHira  the value for public.m_prefecture.name_hira
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public void setNameHira(String nameHira) {
		this.nameHira = nameHira;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_prefecture.name_kana
	 * @return  the value of public.m_prefecture.name_kana
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public String getNameKana() {
		return nameKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_prefecture.name_kana
	 * @param nameKana  the value for public.m_prefecture.name_kana
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public void setNameKana(String nameKana) {
		this.nameKana = nameKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_prefecture.name_roma
	 * @return  the value of public.m_prefecture.name_roma
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public String getNameRoma() {
		return nameRoma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_prefecture.name_roma
	 * @param nameRoma  the value for public.m_prefecture.name_roma
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public void setNameRoma(String nameRoma) {
		this.nameRoma = nameRoma;
	}
}