package com.example.demo.bean.mybatis;

import java.util.ArrayList;
import java.util.List;

public class MPrefectureExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public MPrefectureExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andRecordIdIsNull() {
			addCriterion("record_id is null");
			return (Criteria) this;
		}

		public Criteria andRecordIdIsNotNull() {
			addCriterion("record_id is not null");
			return (Criteria) this;
		}

		public Criteria andRecordIdEqualTo(Long value) {
			addCriterion("record_id =", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotEqualTo(Long value) {
			addCriterion("record_id <>", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdGreaterThan(Long value) {
			addCriterion("record_id >", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdGreaterThanOrEqualTo(Long value) {
			addCriterion("record_id >=", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdLessThan(Long value) {
			addCriterion("record_id <", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdLessThanOrEqualTo(Long value) {
			addCriterion("record_id <=", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdIn(List<Long> values) {
			addCriterion("record_id in", values, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotIn(List<Long> values) {
			addCriterion("record_id not in", values, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdBetween(Long value1, Long value2) {
			addCriterion("record_id between", value1, value2, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotBetween(Long value1, Long value2) {
			addCriterion("record_id not between", value1, value2, "recordId");
			return (Criteria) this;
		}

		public Criteria andNameHiraIsNull() {
			addCriterion("name_hira is null");
			return (Criteria) this;
		}

		public Criteria andNameHiraIsNotNull() {
			addCriterion("name_hira is not null");
			return (Criteria) this;
		}

		public Criteria andNameHiraEqualTo(String value) {
			addCriterion("name_hira =", value, "nameHira");
			return (Criteria) this;
		}

		public Criteria andNameHiraNotEqualTo(String value) {
			addCriterion("name_hira <>", value, "nameHira");
			return (Criteria) this;
		}

		public Criteria andNameHiraGreaterThan(String value) {
			addCriterion("name_hira >", value, "nameHira");
			return (Criteria) this;
		}

		public Criteria andNameHiraGreaterThanOrEqualTo(String value) {
			addCriterion("name_hira >=", value, "nameHira");
			return (Criteria) this;
		}

		public Criteria andNameHiraLessThan(String value) {
			addCriterion("name_hira <", value, "nameHira");
			return (Criteria) this;
		}

		public Criteria andNameHiraLessThanOrEqualTo(String value) {
			addCriterion("name_hira <=", value, "nameHira");
			return (Criteria) this;
		}

		public Criteria andNameHiraLike(String value) {
			addCriterion("name_hira like", value, "nameHira");
			return (Criteria) this;
		}

		public Criteria andNameHiraNotLike(String value) {
			addCriterion("name_hira not like", value, "nameHira");
			return (Criteria) this;
		}

		public Criteria andNameHiraIn(List<String> values) {
			addCriterion("name_hira in", values, "nameHira");
			return (Criteria) this;
		}

		public Criteria andNameHiraNotIn(List<String> values) {
			addCriterion("name_hira not in", values, "nameHira");
			return (Criteria) this;
		}

		public Criteria andNameHiraBetween(String value1, String value2) {
			addCriterion("name_hira between", value1, value2, "nameHira");
			return (Criteria) this;
		}

		public Criteria andNameHiraNotBetween(String value1, String value2) {
			addCriterion("name_hira not between", value1, value2, "nameHira");
			return (Criteria) this;
		}

		public Criteria andNameKanaIsNull() {
			addCriterion("name_kana is null");
			return (Criteria) this;
		}

		public Criteria andNameKanaIsNotNull() {
			addCriterion("name_kana is not null");
			return (Criteria) this;
		}

		public Criteria andNameKanaEqualTo(String value) {
			addCriterion("name_kana =", value, "nameKana");
			return (Criteria) this;
		}

		public Criteria andNameKanaNotEqualTo(String value) {
			addCriterion("name_kana <>", value, "nameKana");
			return (Criteria) this;
		}

		public Criteria andNameKanaGreaterThan(String value) {
			addCriterion("name_kana >", value, "nameKana");
			return (Criteria) this;
		}

		public Criteria andNameKanaGreaterThanOrEqualTo(String value) {
			addCriterion("name_kana >=", value, "nameKana");
			return (Criteria) this;
		}

		public Criteria andNameKanaLessThan(String value) {
			addCriterion("name_kana <", value, "nameKana");
			return (Criteria) this;
		}

		public Criteria andNameKanaLessThanOrEqualTo(String value) {
			addCriterion("name_kana <=", value, "nameKana");
			return (Criteria) this;
		}

		public Criteria andNameKanaLike(String value) {
			addCriterion("name_kana like", value, "nameKana");
			return (Criteria) this;
		}

		public Criteria andNameKanaNotLike(String value) {
			addCriterion("name_kana not like", value, "nameKana");
			return (Criteria) this;
		}

		public Criteria andNameKanaIn(List<String> values) {
			addCriterion("name_kana in", values, "nameKana");
			return (Criteria) this;
		}

		public Criteria andNameKanaNotIn(List<String> values) {
			addCriterion("name_kana not in", values, "nameKana");
			return (Criteria) this;
		}

		public Criteria andNameKanaBetween(String value1, String value2) {
			addCriterion("name_kana between", value1, value2, "nameKana");
			return (Criteria) this;
		}

		public Criteria andNameKanaNotBetween(String value1, String value2) {
			addCriterion("name_kana not between", value1, value2, "nameKana");
			return (Criteria) this;
		}

		public Criteria andNameRomaIsNull() {
			addCriterion("name_roma is null");
			return (Criteria) this;
		}

		public Criteria andNameRomaIsNotNull() {
			addCriterion("name_roma is not null");
			return (Criteria) this;
		}

		public Criteria andNameRomaEqualTo(String value) {
			addCriterion("name_roma =", value, "nameRoma");
			return (Criteria) this;
		}

		public Criteria andNameRomaNotEqualTo(String value) {
			addCriterion("name_roma <>", value, "nameRoma");
			return (Criteria) this;
		}

		public Criteria andNameRomaGreaterThan(String value) {
			addCriterion("name_roma >", value, "nameRoma");
			return (Criteria) this;
		}

		public Criteria andNameRomaGreaterThanOrEqualTo(String value) {
			addCriterion("name_roma >=", value, "nameRoma");
			return (Criteria) this;
		}

		public Criteria andNameRomaLessThan(String value) {
			addCriterion("name_roma <", value, "nameRoma");
			return (Criteria) this;
		}

		public Criteria andNameRomaLessThanOrEqualTo(String value) {
			addCriterion("name_roma <=", value, "nameRoma");
			return (Criteria) this;
		}

		public Criteria andNameRomaLike(String value) {
			addCriterion("name_roma like", value, "nameRoma");
			return (Criteria) this;
		}

		public Criteria andNameRomaNotLike(String value) {
			addCriterion("name_roma not like", value, "nameRoma");
			return (Criteria) this;
		}

		public Criteria andNameRomaIn(List<String> values) {
			addCriterion("name_roma in", values, "nameRoma");
			return (Criteria) this;
		}

		public Criteria andNameRomaNotIn(List<String> values) {
			addCriterion("name_roma not in", values, "nameRoma");
			return (Criteria) this;
		}

		public Criteria andNameRomaBetween(String value1, String value2) {
			addCriterion("name_roma between", value1, value2, "nameRoma");
			return (Criteria) this;
		}

		public Criteria andNameRomaNotBetween(String value1, String value2) {
			addCriterion("name_roma not between", value1, value2, "nameRoma");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.m_prefecture
     *
     * @mbg.generated do_not_delete_during_merge Thu Feb 13 16:41:33 JST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}