package com.example.demo.mapper.mybatis;

import com.example.demo.model.mybatis.MApi;
import com.example.demo.model.mybatis.MApiExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MApiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_api
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    long countByExample(MApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_api
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    int deleteByExample(MApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_api
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    int deleteByPrimaryKey(String apiCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_api
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    int insert(MApi row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_api
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    int insertSelective(MApi row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_api
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    List<MApi> selectByExample(MApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_api
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    MApi selectByPrimaryKey(String apiCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_api
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    int updateByExampleSelective(@Param("row") MApi row, @Param("example") MApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_api
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    int updateByExample(@Param("row") MApi row, @Param("example") MApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_api
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    int updateByPrimaryKeySelective(MApi row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_api
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    int updateByPrimaryKey(MApi row);
}