package com.example.demo.mapper.mybatis;

import com.example.demo.model.mybatis.MGendar;
import com.example.demo.model.mybatis.MGendarExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MGendarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_gendar
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    long countByExample(MGendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_gendar
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    int deleteByExample(MGendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_gendar
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    int deleteByPrimaryKey(String gendarCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_gendar
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    int insert(MGendar row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_gendar
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    int insertSelective(MGendar row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_gendar
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    List<MGendar> selectByExample(MGendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_gendar
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    MGendar selectByPrimaryKey(String gendarCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_gendar
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    int updateByExampleSelective(@Param("row") MGendar row, @Param("example") MGendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_gendar
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    int updateByExample(@Param("row") MGendar row, @Param("example") MGendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_gendar
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    int updateByPrimaryKeySelective(MGendar row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_gendar
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    int updateByPrimaryKey(MGendar row);
}