package com.example.demo.mapper.mybatis;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.bean.mybatis.MGender;
import com.example.demo.bean.mybatis.MGenderExample;

@Mapper
public interface MGenderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	long countByExample(MGenderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	int deleteByExample(MGenderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	int deleteByPrimaryKey(String nameJpn);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	int insert(MGender record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	int insertSelective(MGender record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	List<MGender> selectByExample(MGenderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	MGender selectByPrimaryKey(String nameJpn);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	int updateByExampleSelective(@Param("record") MGender record, @Param("example") MGenderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	int updateByExample(@Param("record") MGender record, @Param("example") MGenderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	int updateByPrimaryKeySelective(MGender record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_gender
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	int updateByPrimaryKey(MGender record);
}