package com.example.demo.mapper.mybatis;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.bean.mybatis.MPrefecture;
import com.example.demo.bean.mybatis.MPrefectureExample;

@Mapper
public interface MPrefectureMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	long countByExample(MPrefectureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	int deleteByExample(MPrefectureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	int deleteByPrimaryKey(String name);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	int insert(MPrefecture record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	int insertSelective(MPrefecture record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	List<MPrefecture> selectByExample(MPrefectureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	MPrefecture selectByPrimaryKey(String name);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	int updateByExampleSelective(@Param("record") MPrefecture record, @Param("example") MPrefectureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	int updateByExample(@Param("record") MPrefecture record, @Param("example") MPrefectureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	int updateByPrimaryKeySelective(MPrefecture record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Thu Feb 13 17:07:37 JST 2020
	 */
	int updateByPrimaryKey(MPrefecture record);
}