package com.example.demo.mapper.mybatis;

import com.example.demo.model.mybatis.MPrefecture;
import com.example.demo.model.mybatis.MPrefectureExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MPrefectureMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	long countByExample(MPrefectureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int deleteByExample(MPrefectureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int deleteByPrimaryKey(String prefectureCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int insert(MPrefecture row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int insertSelective(MPrefecture row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	List<MPrefecture> selectByExample(MPrefectureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	MPrefecture selectByPrimaryKey(String prefectureCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int updateByExampleSelective(@Param("row") MPrefecture row, @Param("example") MPrefectureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int updateByExample(@Param("row") MPrefecture row, @Param("example") MPrefectureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int updateByPrimaryKeySelective(MPrefecture row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_prefecture
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int updateByPrimaryKey(MPrefecture row);
}