package com.example.demo.mapper.mybatis;

import com.example.demo.model.mybatis.MRole;
import com.example.demo.model.mybatis.MRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_role
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	long countByExample(MRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_role
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int deleteByExample(MRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_role
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int deleteByPrimaryKey(String roleCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_role
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int insert(MRole row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_role
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int insertSelective(MRole row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_role
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	List<MRole> selectByExample(MRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_role
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	MRole selectByPrimaryKey(String roleCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_role
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int updateByExampleSelective(@Param("row") MRole row, @Param("example") MRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_role
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int updateByExample(@Param("row") MRole row, @Param("example") MRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_role
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int updateByPrimaryKeySelective(MRole row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_role
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int updateByPrimaryKey(MRole row);
}