package com.example.demo.mapper.mybatis;

import com.example.demo.model.mybatis.MSystemThema;
import com.example.demo.model.mybatis.MSystemThemaExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MSystemThemaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_system_thema
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	long countByExample(MSystemThemaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_system_thema
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int deleteByExample(MSystemThemaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_system_thema
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int deleteByPrimaryKey(String systemThemaCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_system_thema
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int insert(MSystemThema row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_system_thema
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int insertSelective(MSystemThema row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_system_thema
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	List<MSystemThema> selectByExample(MSystemThemaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_system_thema
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	MSystemThema selectByPrimaryKey(String systemThemaCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_system_thema
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int updateByExampleSelective(@Param("row") MSystemThema row, @Param("example") MSystemThemaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_system_thema
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int updateByExample(@Param("row") MSystemThema row, @Param("example") MSystemThemaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_system_thema
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int updateByPrimaryKeySelective(MSystemThema row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_system_thema
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	int updateByPrimaryKey(MSystemThema row);
}