package com.example.demo.mapper.mybatis;

import com.example.demo.model.mybatis.MUserDetail;
import com.example.demo.model.mybatis.MUserDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MUserDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    long countByExample(MUserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int deleteByExample(MUserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int insert(MUserDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int insertSelective(MUserDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    List<MUserDetail> selectByExample(MUserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    MUserDetail selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int updateByExampleSelective(@Param("row") MUserDetail row, @Param("example") MUserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int updateByExample(@Param("row") MUserDetail row, @Param("example") MUserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int updateByPrimaryKeySelective(MUserDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int updateByPrimaryKey(MUserDetail row);
}