package com.example.demo.mapper.mybatis;

import com.example.demo.model.mybatis.TRoleApi;
import com.example.demo.model.mybatis.TRoleApiExample;
import com.example.demo.model.mybatis.TRoleApiKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TRoleApiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_api
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    long countByExample(TRoleApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_api
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int deleteByExample(TRoleApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_api
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int deleteByPrimaryKey(TRoleApiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_api
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int insert(TRoleApi row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_api
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int insertSelective(TRoleApi row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_api
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    List<TRoleApi> selectByExample(TRoleApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_api
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    TRoleApi selectByPrimaryKey(TRoleApiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_api
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int updateByExampleSelective(@Param("row") TRoleApi row, @Param("example") TRoleApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_api
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int updateByExample(@Param("row") TRoleApi row, @Param("example") TRoleApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_api
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int updateByPrimaryKeySelective(TRoleApi row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_api
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int updateByPrimaryKey(TRoleApi row);
}