package com.example.demo.mapper.mybatis;

import com.example.demo.model.mybatis.TRoleMstMenu;
import com.example.demo.model.mybatis.TRoleMstMenuExample;
import com.example.demo.model.mybatis.TRoleMstMenuKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TRoleMstMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_mst_menu
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    long countByExample(TRoleMstMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_mst_menu
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int deleteByExample(TRoleMstMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_mst_menu
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int deleteByPrimaryKey(TRoleMstMenuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_mst_menu
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int insert(TRoleMstMenu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_mst_menu
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int insertSelective(TRoleMstMenu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_mst_menu
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    List<TRoleMstMenu> selectByExample(TRoleMstMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_mst_menu
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    TRoleMstMenu selectByPrimaryKey(TRoleMstMenuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_mst_menu
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int updateByExampleSelective(@Param("row") TRoleMstMenu row, @Param("example") TRoleMstMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_mst_menu
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int updateByExample(@Param("row") TRoleMstMenu row, @Param("example") TRoleMstMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_mst_menu
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int updateByPrimaryKeySelective(TRoleMstMenu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_mst_menu
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    int updateByPrimaryKey(TRoleMstMenu row);
}