package com.example.demo.model.mybatis;

import java.util.Date;

public class MApi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_api.api_cd
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    private String apiCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_api.update_cnt
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    private Integer updateCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_api.api_nm
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    private String apiNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_api.order_no
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    private Integer orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_api.enabled
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_api.insert_user_id
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    private String insertUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_api.insert_timestamp
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    private Date insertTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_api.update_user_id
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_api.update_timestamp
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_api.api_cd
     *
     * @return the value of public.m_api.api_cd
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public String getApiCd() {
        return apiCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_api.api_cd
     *
     * @param apiCd the value for public.m_api.api_cd
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public void setApiCd(String apiCd) {
        this.apiCd = apiCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_api.update_cnt
     *
     * @return the value of public.m_api.update_cnt
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public Integer getUpdateCnt() {
        return updateCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_api.update_cnt
     *
     * @param updateCnt the value for public.m_api.update_cnt
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public void setUpdateCnt(Integer updateCnt) {
        this.updateCnt = updateCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_api.api_nm
     *
     * @return the value of public.m_api.api_nm
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public String getApiNm() {
        return apiNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_api.api_nm
     *
     * @param apiNm the value for public.m_api.api_nm
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public void setApiNm(String apiNm) {
        this.apiNm = apiNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_api.order_no
     *
     * @return the value of public.m_api.order_no
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_api.order_no
     *
     * @param orderNo the value for public.m_api.order_no
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_api.enabled
     *
     * @return the value of public.m_api.enabled
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_api.enabled
     *
     * @param enabled the value for public.m_api.enabled
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_api.insert_user_id
     *
     * @return the value of public.m_api.insert_user_id
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_api.insert_user_id
     *
     * @param insertUserId the value for public.m_api.insert_user_id
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_api.insert_timestamp
     *
     * @return the value of public.m_api.insert_timestamp
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public Date getInsertTimestamp() {
        return insertTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_api.insert_timestamp
     *
     * @param insertTimestamp the value for public.m_api.insert_timestamp
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public void setInsertTimestamp(Date insertTimestamp) {
        this.insertTimestamp = insertTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_api.update_user_id
     *
     * @return the value of public.m_api.update_user_id
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_api.update_user_id
     *
     * @param updateUserId the value for public.m_api.update_user_id
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_api.update_timestamp
     *
     * @return the value of public.m_api.update_timestamp
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_api.update_timestamp
     *
     * @param updateTimestamp the value for public.m_api.update_timestamp
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_api
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MApi other = (MApi) that;
        return (this.getApiCd() == null ? other.getApiCd() == null : this.getApiCd().equals(other.getApiCd()))
            && (this.getUpdateCnt() == null ? other.getUpdateCnt() == null : this.getUpdateCnt().equals(other.getUpdateCnt()))
            && (this.getApiNm() == null ? other.getApiNm() == null : this.getApiNm().equals(other.getApiNm()))
            && (this.getOrderNo() == null ? other.getOrderNo() == null : this.getOrderNo().equals(other.getOrderNo()))
            && (this.getEnabled() == null ? other.getEnabled() == null : this.getEnabled().equals(other.getEnabled()))
            && (this.getInsertUserId() == null ? other.getInsertUserId() == null : this.getInsertUserId().equals(other.getInsertUserId()))
            && (this.getInsertTimestamp() == null ? other.getInsertTimestamp() == null : this.getInsertTimestamp().equals(other.getInsertTimestamp()))
            && (this.getUpdateUserId() == null ? other.getUpdateUserId() == null : this.getUpdateUserId().equals(other.getUpdateUserId()))
            && (this.getUpdateTimestamp() == null ? other.getUpdateTimestamp() == null : this.getUpdateTimestamp().equals(other.getUpdateTimestamp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_api
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getApiCd() == null) ? 0 : getApiCd().hashCode());
        result = prime * result + ((getUpdateCnt() == null) ? 0 : getUpdateCnt().hashCode());
        result = prime * result + ((getApiNm() == null) ? 0 : getApiNm().hashCode());
        result = prime * result + ((getOrderNo() == null) ? 0 : getOrderNo().hashCode());
        result = prime * result + ((getEnabled() == null) ? 0 : getEnabled().hashCode());
        result = prime * result + ((getInsertUserId() == null) ? 0 : getInsertUserId().hashCode());
        result = prime * result + ((getInsertTimestamp() == null) ? 0 : getInsertTimestamp().hashCode());
        result = prime * result + ((getUpdateUserId() == null) ? 0 : getUpdateUserId().hashCode());
        result = prime * result + ((getUpdateTimestamp() == null) ? 0 : getUpdateTimestamp().hashCode());
        return result;
    }
}