package com.example.demo.model.mybatis;

import java.util.Date;

public class MGendar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_gendar.gendar_cd
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    private String gendarCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_gendar.id
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_gendar.update_cnt
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    private Integer updateCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_gendar.gendar_nm
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    private String gendarNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_gendar.order_no
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    private Integer orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_gendar.deleted
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_gendar.insert_user_id
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    private String insertUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_gendar.insert_timestamp
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    private Date insertTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_gendar.update_user_id
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_gendar.update_timestamp
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    private Date updateTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_gendar.delete_user_id
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    private String deleteUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_gendar.delete_timestamp
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    private Date deleteTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_gendar.gendar_cd
     *
     * @return the value of public.m_gendar.gendar_cd
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public String getGendarCd() {
        return gendarCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_gendar.gendar_cd
     *
     * @param gendarCd the value for public.m_gendar.gendar_cd
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public void setGendarCd(String gendarCd) {
        this.gendarCd = gendarCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_gendar.id
     *
     * @return the value of public.m_gendar.id
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_gendar.id
     *
     * @param id the value for public.m_gendar.id
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_gendar.update_cnt
     *
     * @return the value of public.m_gendar.update_cnt
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public Integer getUpdateCnt() {
        return updateCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_gendar.update_cnt
     *
     * @param updateCnt the value for public.m_gendar.update_cnt
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public void setUpdateCnt(Integer updateCnt) {
        this.updateCnt = updateCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_gendar.gendar_nm
     *
     * @return the value of public.m_gendar.gendar_nm
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public String getGendarNm() {
        return gendarNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_gendar.gendar_nm
     *
     * @param gendarNm the value for public.m_gendar.gendar_nm
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public void setGendarNm(String gendarNm) {
        this.gendarNm = gendarNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_gendar.order_no
     *
     * @return the value of public.m_gendar.order_no
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_gendar.order_no
     *
     * @param orderNo the value for public.m_gendar.order_no
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_gendar.deleted
     *
     * @return the value of public.m_gendar.deleted
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_gendar.deleted
     *
     * @param deleted the value for public.m_gendar.deleted
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_gendar.insert_user_id
     *
     * @return the value of public.m_gendar.insert_user_id
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_gendar.insert_user_id
     *
     * @param insertUserId the value for public.m_gendar.insert_user_id
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_gendar.insert_timestamp
     *
     * @return the value of public.m_gendar.insert_timestamp
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public Date getInsertTimestamp() {
        return insertTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_gendar.insert_timestamp
     *
     * @param insertTimestamp the value for public.m_gendar.insert_timestamp
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public void setInsertTimestamp(Date insertTimestamp) {
        this.insertTimestamp = insertTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_gendar.update_user_id
     *
     * @return the value of public.m_gendar.update_user_id
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_gendar.update_user_id
     *
     * @param updateUserId the value for public.m_gendar.update_user_id
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_gendar.update_timestamp
     *
     * @return the value of public.m_gendar.update_timestamp
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_gendar.update_timestamp
     *
     * @param updateTimestamp the value for public.m_gendar.update_timestamp
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_gendar.delete_user_id
     *
     * @return the value of public.m_gendar.delete_user_id
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public String getDeleteUserId() {
        return deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_gendar.delete_user_id
     *
     * @param deleteUserId the value for public.m_gendar.delete_user_id
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public void setDeleteUserId(String deleteUserId) {
        this.deleteUserId = deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_gendar.delete_timestamp
     *
     * @return the value of public.m_gendar.delete_timestamp
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public Date getDeleteTimestamp() {
        return deleteTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_gendar.delete_timestamp
     *
     * @param deleteTimestamp the value for public.m_gendar.delete_timestamp
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public void setDeleteTimestamp(Date deleteTimestamp) {
        this.deleteTimestamp = deleteTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_gendar
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MGendar other = (MGendar) that;
        return (this.getGendarCd() == null ? other.getGendarCd() == null : this.getGendarCd().equals(other.getGendarCd()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUpdateCnt() == null ? other.getUpdateCnt() == null : this.getUpdateCnt().equals(other.getUpdateCnt()))
            && (this.getGendarNm() == null ? other.getGendarNm() == null : this.getGendarNm().equals(other.getGendarNm()))
            && (this.getOrderNo() == null ? other.getOrderNo() == null : this.getOrderNo().equals(other.getOrderNo()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getInsertUserId() == null ? other.getInsertUserId() == null : this.getInsertUserId().equals(other.getInsertUserId()))
            && (this.getInsertTimestamp() == null ? other.getInsertTimestamp() == null : this.getInsertTimestamp().equals(other.getInsertTimestamp()))
            && (this.getUpdateUserId() == null ? other.getUpdateUserId() == null : this.getUpdateUserId().equals(other.getUpdateUserId()))
            && (this.getUpdateTimestamp() == null ? other.getUpdateTimestamp() == null : this.getUpdateTimestamp().equals(other.getUpdateTimestamp()))
            && (this.getDeleteUserId() == null ? other.getDeleteUserId() == null : this.getDeleteUserId().equals(other.getDeleteUserId()))
            && (this.getDeleteTimestamp() == null ? other.getDeleteTimestamp() == null : this.getDeleteTimestamp().equals(other.getDeleteTimestamp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_gendar
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGendarCd() == null) ? 0 : getGendarCd().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUpdateCnt() == null) ? 0 : getUpdateCnt().hashCode());
        result = prime * result + ((getGendarNm() == null) ? 0 : getGendarNm().hashCode());
        result = prime * result + ((getOrderNo() == null) ? 0 : getOrderNo().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getInsertUserId() == null) ? 0 : getInsertUserId().hashCode());
        result = prime * result + ((getInsertTimestamp() == null) ? 0 : getInsertTimestamp().hashCode());
        result = prime * result + ((getUpdateUserId() == null) ? 0 : getUpdateUserId().hashCode());
        result = prime * result + ((getUpdateTimestamp() == null) ? 0 : getUpdateTimestamp().hashCode());
        result = prime * result + ((getDeleteUserId() == null) ? 0 : getDeleteUserId().hashCode());
        result = prime * result + ((getDeleteTimestamp() == null) ? 0 : getDeleteTimestamp().hashCode());
        return result;
    }
}