package com.example.demo.model.mybatis;

import java.util.Date;

public class MSystemThema {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_system_thema.system_thema_cd
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	private String systemThemaCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_system_thema.id
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_system_thema.update_cnt
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	private Integer updateCnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_system_thema.system_thema_nm
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	private String systemThemaNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_system_thema.order_no
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	private Integer orderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_system_thema.deleted
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	private Boolean deleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_system_thema.insert_user_id
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	private String insertUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_system_thema.insert_timestamp
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	private Date insertTimestamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_system_thema.update_user_id
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	private String updateUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_system_thema.update_timestamp
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	private Date updateTimestamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_system_thema.delete_user_id
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	private String deleteUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.m_system_thema.delete_timestamp
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	private Date deleteTimestamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_system_thema.system_thema_cd
	 * @return  the value of public.m_system_thema.system_thema_cd
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public String getSystemThemaCd() {
		return systemThemaCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_system_thema.system_thema_cd
	 * @param systemThemaCd  the value for public.m_system_thema.system_thema_cd
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public void setSystemThemaCd(String systemThemaCd) {
		this.systemThemaCd = systemThemaCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_system_thema.id
	 * @return  the value of public.m_system_thema.id
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_system_thema.id
	 * @param id  the value for public.m_system_thema.id
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_system_thema.update_cnt
	 * @return  the value of public.m_system_thema.update_cnt
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public Integer getUpdateCnt() {
		return updateCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_system_thema.update_cnt
	 * @param updateCnt  the value for public.m_system_thema.update_cnt
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public void setUpdateCnt(Integer updateCnt) {
		this.updateCnt = updateCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_system_thema.system_thema_nm
	 * @return  the value of public.m_system_thema.system_thema_nm
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public String getSystemThemaNm() {
		return systemThemaNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_system_thema.system_thema_nm
	 * @param systemThemaNm  the value for public.m_system_thema.system_thema_nm
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public void setSystemThemaNm(String systemThemaNm) {
		this.systemThemaNm = systemThemaNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_system_thema.order_no
	 * @return  the value of public.m_system_thema.order_no
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public Integer getOrderNo() {
		return orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_system_thema.order_no
	 * @param orderNo  the value for public.m_system_thema.order_no
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public void setOrderNo(Integer orderNo) {
		this.orderNo = orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_system_thema.deleted
	 * @return  the value of public.m_system_thema.deleted
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public Boolean getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_system_thema.deleted
	 * @param deleted  the value for public.m_system_thema.deleted
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_system_thema.insert_user_id
	 * @return  the value of public.m_system_thema.insert_user_id
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public String getInsertUserId() {
		return insertUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_system_thema.insert_user_id
	 * @param insertUserId  the value for public.m_system_thema.insert_user_id
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public void setInsertUserId(String insertUserId) {
		this.insertUserId = insertUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_system_thema.insert_timestamp
	 * @return  the value of public.m_system_thema.insert_timestamp
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public Date getInsertTimestamp() {
		return insertTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_system_thema.insert_timestamp
	 * @param insertTimestamp  the value for public.m_system_thema.insert_timestamp
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public void setInsertTimestamp(Date insertTimestamp) {
		this.insertTimestamp = insertTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_system_thema.update_user_id
	 * @return  the value of public.m_system_thema.update_user_id
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public String getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_system_thema.update_user_id
	 * @param updateUserId  the value for public.m_system_thema.update_user_id
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public void setUpdateUserId(String updateUserId) {
		this.updateUserId = updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_system_thema.update_timestamp
	 * @return  the value of public.m_system_thema.update_timestamp
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public Date getUpdateTimestamp() {
		return updateTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_system_thema.update_timestamp
	 * @param updateTimestamp  the value for public.m_system_thema.update_timestamp
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_system_thema.delete_user_id
	 * @return  the value of public.m_system_thema.delete_user_id
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public String getDeleteUserId() {
		return deleteUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_system_thema.delete_user_id
	 * @param deleteUserId  the value for public.m_system_thema.delete_user_id
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public void setDeleteUserId(String deleteUserId) {
		this.deleteUserId = deleteUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.m_system_thema.delete_timestamp
	 * @return  the value of public.m_system_thema.delete_timestamp
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public Date getDeleteTimestamp() {
		return deleteTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.m_system_thema.delete_timestamp
	 * @param deleteTimestamp  the value for public.m_system_thema.delete_timestamp
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	public void setDeleteTimestamp(Date deleteTimestamp) {
		this.deleteTimestamp = deleteTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_system_thema
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		MSystemThema other = (MSystemThema) that;
		return (this.getSystemThemaCd() == null ? other.getSystemThemaCd() == null
				: this.getSystemThemaCd().equals(other.getSystemThemaCd()))
				&& (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getUpdateCnt() == null ? other.getUpdateCnt() == null
						: this.getUpdateCnt().equals(other.getUpdateCnt()))
				&& (this.getSystemThemaNm() == null ? other.getSystemThemaNm() == null
						: this.getSystemThemaNm().equals(other.getSystemThemaNm()))
				&& (this.getOrderNo() == null ? other.getOrderNo() == null
						: this.getOrderNo().equals(other.getOrderNo()))
				&& (this.getDeleted() == null ? other.getDeleted() == null
						: this.getDeleted().equals(other.getDeleted()))
				&& (this.getInsertUserId() == null ? other.getInsertUserId() == null
						: this.getInsertUserId().equals(other.getInsertUserId()))
				&& (this.getInsertTimestamp() == null ? other.getInsertTimestamp() == null
						: this.getInsertTimestamp().equals(other.getInsertTimestamp()))
				&& (this.getUpdateUserId() == null ? other.getUpdateUserId() == null
						: this.getUpdateUserId().equals(other.getUpdateUserId()))
				&& (this.getUpdateTimestamp() == null ? other.getUpdateTimestamp() == null
						: this.getUpdateTimestamp().equals(other.getUpdateTimestamp()))
				&& (this.getDeleteUserId() == null ? other.getDeleteUserId() == null
						: this.getDeleteUserId().equals(other.getDeleteUserId()))
				&& (this.getDeleteTimestamp() == null ? other.getDeleteTimestamp() == null
						: this.getDeleteTimestamp().equals(other.getDeleteTimestamp()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.m_system_thema
	 * @mbg.generated  Sat Nov 26 13:37:05 JST 2022
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSystemThemaCd() == null) ? 0 : getSystemThemaCd().hashCode());
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getUpdateCnt() == null) ? 0 : getUpdateCnt().hashCode());
		result = prime * result + ((getSystemThemaNm() == null) ? 0 : getSystemThemaNm().hashCode());
		result = prime * result + ((getOrderNo() == null) ? 0 : getOrderNo().hashCode());
		result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
		result = prime * result + ((getInsertUserId() == null) ? 0 : getInsertUserId().hashCode());
		result = prime * result + ((getInsertTimestamp() == null) ? 0 : getInsertTimestamp().hashCode());
		result = prime * result + ((getUpdateUserId() == null) ? 0 : getUpdateUserId().hashCode());
		result = prime * result + ((getUpdateTimestamp() == null) ? 0 : getUpdateTimestamp().hashCode());
		result = prime * result + ((getDeleteUserId() == null) ? 0 : getDeleteUserId().hashCode());
		result = prime * result + ((getDeleteTimestamp() == null) ? 0 : getDeleteTimestamp().hashCode());
		return result;
	}
}