package com.example.demo.model.mybatis;

import java.util.Date;

public class MSystemThema {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_system_thema.system_thema_cd
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    private String systemThemaCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_system_thema.update_cnt
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    private Integer updateCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_system_thema.system_thema_nm
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    private String systemThemaNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_system_thema.order_no
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    private Integer orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_system_thema.enabled
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_system_thema.insert_user_id
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    private String insertUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_system_thema.insert_timestamp
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    private Date insertTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_system_thema.update_user_id
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_system_thema.update_timestamp
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_system_thema.system_thema_cd
     *
     * @return the value of public.m_system_thema.system_thema_cd
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public String getSystemThemaCd() {
        return systemThemaCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_system_thema.system_thema_cd
     *
     * @param systemThemaCd the value for public.m_system_thema.system_thema_cd
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public void setSystemThemaCd(String systemThemaCd) {
        this.systemThemaCd = systemThemaCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_system_thema.update_cnt
     *
     * @return the value of public.m_system_thema.update_cnt
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public Integer getUpdateCnt() {
        return updateCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_system_thema.update_cnt
     *
     * @param updateCnt the value for public.m_system_thema.update_cnt
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public void setUpdateCnt(Integer updateCnt) {
        this.updateCnt = updateCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_system_thema.system_thema_nm
     *
     * @return the value of public.m_system_thema.system_thema_nm
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public String getSystemThemaNm() {
        return systemThemaNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_system_thema.system_thema_nm
     *
     * @param systemThemaNm the value for public.m_system_thema.system_thema_nm
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public void setSystemThemaNm(String systemThemaNm) {
        this.systemThemaNm = systemThemaNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_system_thema.order_no
     *
     * @return the value of public.m_system_thema.order_no
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_system_thema.order_no
     *
     * @param orderNo the value for public.m_system_thema.order_no
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_system_thema.enabled
     *
     * @return the value of public.m_system_thema.enabled
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_system_thema.enabled
     *
     * @param enabled the value for public.m_system_thema.enabled
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_system_thema.insert_user_id
     *
     * @return the value of public.m_system_thema.insert_user_id
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_system_thema.insert_user_id
     *
     * @param insertUserId the value for public.m_system_thema.insert_user_id
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_system_thema.insert_timestamp
     *
     * @return the value of public.m_system_thema.insert_timestamp
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public Date getInsertTimestamp() {
        return insertTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_system_thema.insert_timestamp
     *
     * @param insertTimestamp the value for public.m_system_thema.insert_timestamp
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public void setInsertTimestamp(Date insertTimestamp) {
        this.insertTimestamp = insertTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_system_thema.update_user_id
     *
     * @return the value of public.m_system_thema.update_user_id
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_system_thema.update_user_id
     *
     * @param updateUserId the value for public.m_system_thema.update_user_id
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_system_thema.update_timestamp
     *
     * @return the value of public.m_system_thema.update_timestamp
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_system_thema.update_timestamp
     *
     * @param updateTimestamp the value for public.m_system_thema.update_timestamp
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_system_thema
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MSystemThema other = (MSystemThema) that;
        return (this.getSystemThemaCd() == null ? other.getSystemThemaCd() == null : this.getSystemThemaCd().equals(other.getSystemThemaCd()))
            && (this.getUpdateCnt() == null ? other.getUpdateCnt() == null : this.getUpdateCnt().equals(other.getUpdateCnt()))
            && (this.getSystemThemaNm() == null ? other.getSystemThemaNm() == null : this.getSystemThemaNm().equals(other.getSystemThemaNm()))
            && (this.getOrderNo() == null ? other.getOrderNo() == null : this.getOrderNo().equals(other.getOrderNo()))
            && (this.getEnabled() == null ? other.getEnabled() == null : this.getEnabled().equals(other.getEnabled()))
            && (this.getInsertUserId() == null ? other.getInsertUserId() == null : this.getInsertUserId().equals(other.getInsertUserId()))
            && (this.getInsertTimestamp() == null ? other.getInsertTimestamp() == null : this.getInsertTimestamp().equals(other.getInsertTimestamp()))
            && (this.getUpdateUserId() == null ? other.getUpdateUserId() == null : this.getUpdateUserId().equals(other.getUpdateUserId()))
            && (this.getUpdateTimestamp() == null ? other.getUpdateTimestamp() == null : this.getUpdateTimestamp().equals(other.getUpdateTimestamp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_system_thema
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSystemThemaCd() == null) ? 0 : getSystemThemaCd().hashCode());
        result = prime * result + ((getUpdateCnt() == null) ? 0 : getUpdateCnt().hashCode());
        result = prime * result + ((getSystemThemaNm() == null) ? 0 : getSystemThemaNm().hashCode());
        result = prime * result + ((getOrderNo() == null) ? 0 : getOrderNo().hashCode());
        result = prime * result + ((getEnabled() == null) ? 0 : getEnabled().hashCode());
        result = prime * result + ((getInsertUserId() == null) ? 0 : getInsertUserId().hashCode());
        result = prime * result + ((getInsertTimestamp() == null) ? 0 : getInsertTimestamp().hashCode());
        result = prime * result + ((getUpdateUserId() == null) ? 0 : getUpdateUserId().hashCode());
        result = prime * result + ((getUpdateTimestamp() == null) ? 0 : getUpdateTimestamp().hashCode());
        return result;
    }
}