package com.example.demo.model.mybatis;

import java.util.Date;

public class MUserDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.user_id
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.update_cnt
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private Integer updateCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.last_nm
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private String lastNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.first_nm
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private String firstNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.last_nm_kana
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private String lastNmKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.first_nm_kana
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private String firstNmKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.gender
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.phone_no
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.mobile_phone_no
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private String mobilePhoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.mail_address
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private String mailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.post_no
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private String postNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.prefecture
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private String prefecture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.address
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.address_kana
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private String addressKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.date_of_birth
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private Date dateOfBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.blood_type
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private String bloodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.system_thema_cd
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private String systemThemaCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.insert_user_id
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private String insertUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.insert_timestamp
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private Date insertTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.update_user_id
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user_detail.update_timestamp
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.user_id
     *
     * @return the value of public.m_user_detail.user_id
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.user_id
     *
     * @param userId the value for public.m_user_detail.user_id
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.update_cnt
     *
     * @return the value of public.m_user_detail.update_cnt
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public Integer getUpdateCnt() {
        return updateCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.update_cnt
     *
     * @param updateCnt the value for public.m_user_detail.update_cnt
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setUpdateCnt(Integer updateCnt) {
        this.updateCnt = updateCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.last_nm
     *
     * @return the value of public.m_user_detail.last_nm
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public String getLastNm() {
        return lastNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.last_nm
     *
     * @param lastNm the value for public.m_user_detail.last_nm
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setLastNm(String lastNm) {
        this.lastNm = lastNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.first_nm
     *
     * @return the value of public.m_user_detail.first_nm
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public String getFirstNm() {
        return firstNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.first_nm
     *
     * @param firstNm the value for public.m_user_detail.first_nm
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setFirstNm(String firstNm) {
        this.firstNm = firstNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.last_nm_kana
     *
     * @return the value of public.m_user_detail.last_nm_kana
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public String getLastNmKana() {
        return lastNmKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.last_nm_kana
     *
     * @param lastNmKana the value for public.m_user_detail.last_nm_kana
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setLastNmKana(String lastNmKana) {
        this.lastNmKana = lastNmKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.first_nm_kana
     *
     * @return the value of public.m_user_detail.first_nm_kana
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public String getFirstNmKana() {
        return firstNmKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.first_nm_kana
     *
     * @param firstNmKana the value for public.m_user_detail.first_nm_kana
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setFirstNmKana(String firstNmKana) {
        this.firstNmKana = firstNmKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.gender
     *
     * @return the value of public.m_user_detail.gender
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.gender
     *
     * @param gender the value for public.m_user_detail.gender
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.phone_no
     *
     * @return the value of public.m_user_detail.phone_no
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.phone_no
     *
     * @param phoneNo the value for public.m_user_detail.phone_no
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.mobile_phone_no
     *
     * @return the value of public.m_user_detail.mobile_phone_no
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public String getMobilePhoneNo() {
        return mobilePhoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.mobile_phone_no
     *
     * @param mobilePhoneNo the value for public.m_user_detail.mobile_phone_no
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setMobilePhoneNo(String mobilePhoneNo) {
        this.mobilePhoneNo = mobilePhoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.mail_address
     *
     * @return the value of public.m_user_detail.mail_address
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public String getMailAddress() {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.mail_address
     *
     * @param mailAddress the value for public.m_user_detail.mail_address
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.post_no
     *
     * @return the value of public.m_user_detail.post_no
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public String getPostNo() {
        return postNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.post_no
     *
     * @param postNo the value for public.m_user_detail.post_no
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setPostNo(String postNo) {
        this.postNo = postNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.prefecture
     *
     * @return the value of public.m_user_detail.prefecture
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public String getPrefecture() {
        return prefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.prefecture
     *
     * @param prefecture the value for public.m_user_detail.prefecture
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setPrefecture(String prefecture) {
        this.prefecture = prefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.address
     *
     * @return the value of public.m_user_detail.address
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.address
     *
     * @param address the value for public.m_user_detail.address
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.address_kana
     *
     * @return the value of public.m_user_detail.address_kana
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public String getAddressKana() {
        return addressKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.address_kana
     *
     * @param addressKana the value for public.m_user_detail.address_kana
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setAddressKana(String addressKana) {
        this.addressKana = addressKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.date_of_birth
     *
     * @return the value of public.m_user_detail.date_of_birth
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.date_of_birth
     *
     * @param dateOfBirth the value for public.m_user_detail.date_of_birth
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.blood_type
     *
     * @return the value of public.m_user_detail.blood_type
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public String getBloodType() {
        return bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.blood_type
     *
     * @param bloodType the value for public.m_user_detail.blood_type
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.system_thema_cd
     *
     * @return the value of public.m_user_detail.system_thema_cd
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public String getSystemThemaCd() {
        return systemThemaCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.system_thema_cd
     *
     * @param systemThemaCd the value for public.m_user_detail.system_thema_cd
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setSystemThemaCd(String systemThemaCd) {
        this.systemThemaCd = systemThemaCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.insert_user_id
     *
     * @return the value of public.m_user_detail.insert_user_id
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.insert_user_id
     *
     * @param insertUserId the value for public.m_user_detail.insert_user_id
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.insert_timestamp
     *
     * @return the value of public.m_user_detail.insert_timestamp
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public Date getInsertTimestamp() {
        return insertTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.insert_timestamp
     *
     * @param insertTimestamp the value for public.m_user_detail.insert_timestamp
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setInsertTimestamp(Date insertTimestamp) {
        this.insertTimestamp = insertTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.update_user_id
     *
     * @return the value of public.m_user_detail.update_user_id
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.update_user_id
     *
     * @param updateUserId the value for public.m_user_detail.update_user_id
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user_detail.update_timestamp
     *
     * @return the value of public.m_user_detail.update_timestamp
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user_detail.update_timestamp
     *
     * @param updateTimestamp the value for public.m_user_detail.update_timestamp
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MUserDetail other = (MUserDetail) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUpdateCnt() == null ? other.getUpdateCnt() == null : this.getUpdateCnt().equals(other.getUpdateCnt()))
            && (this.getLastNm() == null ? other.getLastNm() == null : this.getLastNm().equals(other.getLastNm()))
            && (this.getFirstNm() == null ? other.getFirstNm() == null : this.getFirstNm().equals(other.getFirstNm()))
            && (this.getLastNmKana() == null ? other.getLastNmKana() == null : this.getLastNmKana().equals(other.getLastNmKana()))
            && (this.getFirstNmKana() == null ? other.getFirstNmKana() == null : this.getFirstNmKana().equals(other.getFirstNmKana()))
            && (this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
            && (this.getPhoneNo() == null ? other.getPhoneNo() == null : this.getPhoneNo().equals(other.getPhoneNo()))
            && (this.getMobilePhoneNo() == null ? other.getMobilePhoneNo() == null : this.getMobilePhoneNo().equals(other.getMobilePhoneNo()))
            && (this.getMailAddress() == null ? other.getMailAddress() == null : this.getMailAddress().equals(other.getMailAddress()))
            && (this.getPostNo() == null ? other.getPostNo() == null : this.getPostNo().equals(other.getPostNo()))
            && (this.getPrefecture() == null ? other.getPrefecture() == null : this.getPrefecture().equals(other.getPrefecture()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getAddressKana() == null ? other.getAddressKana() == null : this.getAddressKana().equals(other.getAddressKana()))
            && (this.getDateOfBirth() == null ? other.getDateOfBirth() == null : this.getDateOfBirth().equals(other.getDateOfBirth()))
            && (this.getBloodType() == null ? other.getBloodType() == null : this.getBloodType().equals(other.getBloodType()))
            && (this.getSystemThemaCd() == null ? other.getSystemThemaCd() == null : this.getSystemThemaCd().equals(other.getSystemThemaCd()))
            && (this.getInsertUserId() == null ? other.getInsertUserId() == null : this.getInsertUserId().equals(other.getInsertUserId()))
            && (this.getInsertTimestamp() == null ? other.getInsertTimestamp() == null : this.getInsertTimestamp().equals(other.getInsertTimestamp()))
            && (this.getUpdateUserId() == null ? other.getUpdateUserId() == null : this.getUpdateUserId().equals(other.getUpdateUserId()))
            && (this.getUpdateTimestamp() == null ? other.getUpdateTimestamp() == null : this.getUpdateTimestamp().equals(other.getUpdateTimestamp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Dec 03 15:56:22 JST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUpdateCnt() == null) ? 0 : getUpdateCnt().hashCode());
        result = prime * result + ((getLastNm() == null) ? 0 : getLastNm().hashCode());
        result = prime * result + ((getFirstNm() == null) ? 0 : getFirstNm().hashCode());
        result = prime * result + ((getLastNmKana() == null) ? 0 : getLastNmKana().hashCode());
        result = prime * result + ((getFirstNmKana() == null) ? 0 : getFirstNmKana().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getPhoneNo() == null) ? 0 : getPhoneNo().hashCode());
        result = prime * result + ((getMobilePhoneNo() == null) ? 0 : getMobilePhoneNo().hashCode());
        result = prime * result + ((getMailAddress() == null) ? 0 : getMailAddress().hashCode());
        result = prime * result + ((getPostNo() == null) ? 0 : getPostNo().hashCode());
        result = prime * result + ((getPrefecture() == null) ? 0 : getPrefecture().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getAddressKana() == null) ? 0 : getAddressKana().hashCode());
        result = prime * result + ((getDateOfBirth() == null) ? 0 : getDateOfBirth().hashCode());
        result = prime * result + ((getBloodType() == null) ? 0 : getBloodType().hashCode());
        result = prime * result + ((getSystemThemaCd() == null) ? 0 : getSystemThemaCd().hashCode());
        result = prime * result + ((getInsertUserId() == null) ? 0 : getInsertUserId().hashCode());
        result = prime * result + ((getInsertTimestamp() == null) ? 0 : getInsertTimestamp().hashCode());
        result = prime * result + ((getUpdateUserId() == null) ? 0 : getUpdateUserId().hashCode());
        result = prime * result + ((getUpdateTimestamp() == null) ? 0 : getUpdateTimestamp().hashCode());
        return result;
    }
}