package com.example.demo.model.mybatis;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MUserDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public MUserDetailExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUpdateCntIsNull() {
            addCriterion("update_cnt is null");
            return (Criteria) this;
        }

        public Criteria andUpdateCntIsNotNull() {
            addCriterion("update_cnt is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateCntEqualTo(Integer value) {
            addCriterion("update_cnt =", value, "updateCnt");
            return (Criteria) this;
        }

        public Criteria andUpdateCntNotEqualTo(Integer value) {
            addCriterion("update_cnt <>", value, "updateCnt");
            return (Criteria) this;
        }

        public Criteria andUpdateCntGreaterThan(Integer value) {
            addCriterion("update_cnt >", value, "updateCnt");
            return (Criteria) this;
        }

        public Criteria andUpdateCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_cnt >=", value, "updateCnt");
            return (Criteria) this;
        }

        public Criteria andUpdateCntLessThan(Integer value) {
            addCriterion("update_cnt <", value, "updateCnt");
            return (Criteria) this;
        }

        public Criteria andUpdateCntLessThanOrEqualTo(Integer value) {
            addCriterion("update_cnt <=", value, "updateCnt");
            return (Criteria) this;
        }

        public Criteria andUpdateCntIn(List<Integer> values) {
            addCriterion("update_cnt in", values, "updateCnt");
            return (Criteria) this;
        }

        public Criteria andUpdateCntNotIn(List<Integer> values) {
            addCriterion("update_cnt not in", values, "updateCnt");
            return (Criteria) this;
        }

        public Criteria andUpdateCntBetween(Integer value1, Integer value2) {
            addCriterion("update_cnt between", value1, value2, "updateCnt");
            return (Criteria) this;
        }

        public Criteria andUpdateCntNotBetween(Integer value1, Integer value2) {
            addCriterion("update_cnt not between", value1, value2, "updateCnt");
            return (Criteria) this;
        }

        public Criteria andLastNmIsNull() {
            addCriterion("last_nm is null");
            return (Criteria) this;
        }

        public Criteria andLastNmIsNotNull() {
            addCriterion("last_nm is not null");
            return (Criteria) this;
        }

        public Criteria andLastNmEqualTo(String value) {
            addCriterion("last_nm =", value, "lastNm");
            return (Criteria) this;
        }

        public Criteria andLastNmNotEqualTo(String value) {
            addCriterion("last_nm <>", value, "lastNm");
            return (Criteria) this;
        }

        public Criteria andLastNmGreaterThan(String value) {
            addCriterion("last_nm >", value, "lastNm");
            return (Criteria) this;
        }

        public Criteria andLastNmGreaterThanOrEqualTo(String value) {
            addCriterion("last_nm >=", value, "lastNm");
            return (Criteria) this;
        }

        public Criteria andLastNmLessThan(String value) {
            addCriterion("last_nm <", value, "lastNm");
            return (Criteria) this;
        }

        public Criteria andLastNmLessThanOrEqualTo(String value) {
            addCriterion("last_nm <=", value, "lastNm");
            return (Criteria) this;
        }

        public Criteria andLastNmLike(String value) {
            addCriterion("last_nm like", value, "lastNm");
            return (Criteria) this;
        }

        public Criteria andLastNmNotLike(String value) {
            addCriterion("last_nm not like", value, "lastNm");
            return (Criteria) this;
        }

        public Criteria andLastNmIn(List<String> values) {
            addCriterion("last_nm in", values, "lastNm");
            return (Criteria) this;
        }

        public Criteria andLastNmNotIn(List<String> values) {
            addCriterion("last_nm not in", values, "lastNm");
            return (Criteria) this;
        }

        public Criteria andLastNmBetween(String value1, String value2) {
            addCriterion("last_nm between", value1, value2, "lastNm");
            return (Criteria) this;
        }

        public Criteria andLastNmNotBetween(String value1, String value2) {
            addCriterion("last_nm not between", value1, value2, "lastNm");
            return (Criteria) this;
        }

        public Criteria andFirstNmIsNull() {
            addCriterion("first_nm is null");
            return (Criteria) this;
        }

        public Criteria andFirstNmIsNotNull() {
            addCriterion("first_nm is not null");
            return (Criteria) this;
        }

        public Criteria andFirstNmEqualTo(String value) {
            addCriterion("first_nm =", value, "firstNm");
            return (Criteria) this;
        }

        public Criteria andFirstNmNotEqualTo(String value) {
            addCriterion("first_nm <>", value, "firstNm");
            return (Criteria) this;
        }

        public Criteria andFirstNmGreaterThan(String value) {
            addCriterion("first_nm >", value, "firstNm");
            return (Criteria) this;
        }

        public Criteria andFirstNmGreaterThanOrEqualTo(String value) {
            addCriterion("first_nm >=", value, "firstNm");
            return (Criteria) this;
        }

        public Criteria andFirstNmLessThan(String value) {
            addCriterion("first_nm <", value, "firstNm");
            return (Criteria) this;
        }

        public Criteria andFirstNmLessThanOrEqualTo(String value) {
            addCriterion("first_nm <=", value, "firstNm");
            return (Criteria) this;
        }

        public Criteria andFirstNmLike(String value) {
            addCriterion("first_nm like", value, "firstNm");
            return (Criteria) this;
        }

        public Criteria andFirstNmNotLike(String value) {
            addCriterion("first_nm not like", value, "firstNm");
            return (Criteria) this;
        }

        public Criteria andFirstNmIn(List<String> values) {
            addCriterion("first_nm in", values, "firstNm");
            return (Criteria) this;
        }

        public Criteria andFirstNmNotIn(List<String> values) {
            addCriterion("first_nm not in", values, "firstNm");
            return (Criteria) this;
        }

        public Criteria andFirstNmBetween(String value1, String value2) {
            addCriterion("first_nm between", value1, value2, "firstNm");
            return (Criteria) this;
        }

        public Criteria andFirstNmNotBetween(String value1, String value2) {
            addCriterion("first_nm not between", value1, value2, "firstNm");
            return (Criteria) this;
        }

        public Criteria andLastNmKanaIsNull() {
            addCriterion("last_nm_kana is null");
            return (Criteria) this;
        }

        public Criteria andLastNmKanaIsNotNull() {
            addCriterion("last_nm_kana is not null");
            return (Criteria) this;
        }

        public Criteria andLastNmKanaEqualTo(String value) {
            addCriterion("last_nm_kana =", value, "lastNmKana");
            return (Criteria) this;
        }

        public Criteria andLastNmKanaNotEqualTo(String value) {
            addCriterion("last_nm_kana <>", value, "lastNmKana");
            return (Criteria) this;
        }

        public Criteria andLastNmKanaGreaterThan(String value) {
            addCriterion("last_nm_kana >", value, "lastNmKana");
            return (Criteria) this;
        }

        public Criteria andLastNmKanaGreaterThanOrEqualTo(String value) {
            addCriterion("last_nm_kana >=", value, "lastNmKana");
            return (Criteria) this;
        }

        public Criteria andLastNmKanaLessThan(String value) {
            addCriterion("last_nm_kana <", value, "lastNmKana");
            return (Criteria) this;
        }

        public Criteria andLastNmKanaLessThanOrEqualTo(String value) {
            addCriterion("last_nm_kana <=", value, "lastNmKana");
            return (Criteria) this;
        }

        public Criteria andLastNmKanaLike(String value) {
            addCriterion("last_nm_kana like", value, "lastNmKana");
            return (Criteria) this;
        }

        public Criteria andLastNmKanaNotLike(String value) {
            addCriterion("last_nm_kana not like", value, "lastNmKana");
            return (Criteria) this;
        }

        public Criteria andLastNmKanaIn(List<String> values) {
            addCriterion("last_nm_kana in", values, "lastNmKana");
            return (Criteria) this;
        }

        public Criteria andLastNmKanaNotIn(List<String> values) {
            addCriterion("last_nm_kana not in", values, "lastNmKana");
            return (Criteria) this;
        }

        public Criteria andLastNmKanaBetween(String value1, String value2) {
            addCriterion("last_nm_kana between", value1, value2, "lastNmKana");
            return (Criteria) this;
        }

        public Criteria andLastNmKanaNotBetween(String value1, String value2) {
            addCriterion("last_nm_kana not between", value1, value2, "lastNmKana");
            return (Criteria) this;
        }

        public Criteria andFirstNmKanaIsNull() {
            addCriterion("first_nm_kana is null");
            return (Criteria) this;
        }

        public Criteria andFirstNmKanaIsNotNull() {
            addCriterion("first_nm_kana is not null");
            return (Criteria) this;
        }

        public Criteria andFirstNmKanaEqualTo(String value) {
            addCriterion("first_nm_kana =", value, "firstNmKana");
            return (Criteria) this;
        }

        public Criteria andFirstNmKanaNotEqualTo(String value) {
            addCriterion("first_nm_kana <>", value, "firstNmKana");
            return (Criteria) this;
        }

        public Criteria andFirstNmKanaGreaterThan(String value) {
            addCriterion("first_nm_kana >", value, "firstNmKana");
            return (Criteria) this;
        }

        public Criteria andFirstNmKanaGreaterThanOrEqualTo(String value) {
            addCriterion("first_nm_kana >=", value, "firstNmKana");
            return (Criteria) this;
        }

        public Criteria andFirstNmKanaLessThan(String value) {
            addCriterion("first_nm_kana <", value, "firstNmKana");
            return (Criteria) this;
        }

        public Criteria andFirstNmKanaLessThanOrEqualTo(String value) {
            addCriterion("first_nm_kana <=", value, "firstNmKana");
            return (Criteria) this;
        }

        public Criteria andFirstNmKanaLike(String value) {
            addCriterion("first_nm_kana like", value, "firstNmKana");
            return (Criteria) this;
        }

        public Criteria andFirstNmKanaNotLike(String value) {
            addCriterion("first_nm_kana not like", value, "firstNmKana");
            return (Criteria) this;
        }

        public Criteria andFirstNmKanaIn(List<String> values) {
            addCriterion("first_nm_kana in", values, "firstNmKana");
            return (Criteria) this;
        }

        public Criteria andFirstNmKanaNotIn(List<String> values) {
            addCriterion("first_nm_kana not in", values, "firstNmKana");
            return (Criteria) this;
        }

        public Criteria andFirstNmKanaBetween(String value1, String value2) {
            addCriterion("first_nm_kana between", value1, value2, "firstNmKana");
            return (Criteria) this;
        }

        public Criteria andFirstNmKanaNotBetween(String value1, String value2) {
            addCriterion("first_nm_kana not between", value1, value2, "firstNmKana");
            return (Criteria) this;
        }

        public Criteria andGendarCdIsNull() {
            addCriterion("gendar_cd is null");
            return (Criteria) this;
        }

        public Criteria andGendarCdIsNotNull() {
            addCriterion("gendar_cd is not null");
            return (Criteria) this;
        }

        public Criteria andGendarCdEqualTo(String value) {
            addCriterion("gendar_cd =", value, "gendarCd");
            return (Criteria) this;
        }

        public Criteria andGendarCdNotEqualTo(String value) {
            addCriterion("gendar_cd <>", value, "gendarCd");
            return (Criteria) this;
        }

        public Criteria andGendarCdGreaterThan(String value) {
            addCriterion("gendar_cd >", value, "gendarCd");
            return (Criteria) this;
        }

        public Criteria andGendarCdGreaterThanOrEqualTo(String value) {
            addCriterion("gendar_cd >=", value, "gendarCd");
            return (Criteria) this;
        }

        public Criteria andGendarCdLessThan(String value) {
            addCriterion("gendar_cd <", value, "gendarCd");
            return (Criteria) this;
        }

        public Criteria andGendarCdLessThanOrEqualTo(String value) {
            addCriterion("gendar_cd <=", value, "gendarCd");
            return (Criteria) this;
        }

        public Criteria andGendarCdLike(String value) {
            addCriterion("gendar_cd like", value, "gendarCd");
            return (Criteria) this;
        }

        public Criteria andGendarCdNotLike(String value) {
            addCriterion("gendar_cd not like", value, "gendarCd");
            return (Criteria) this;
        }

        public Criteria andGendarCdIn(List<String> values) {
            addCriterion("gendar_cd in", values, "gendarCd");
            return (Criteria) this;
        }

        public Criteria andGendarCdNotIn(List<String> values) {
            addCriterion("gendar_cd not in", values, "gendarCd");
            return (Criteria) this;
        }

        public Criteria andGendarCdBetween(String value1, String value2) {
            addCriterion("gendar_cd between", value1, value2, "gendarCd");
            return (Criteria) this;
        }

        public Criteria andGendarCdNotBetween(String value1, String value2) {
            addCriterion("gendar_cd not between", value1, value2, "gendarCd");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIsNull() {
            addCriterion("phone_no is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIsNotNull() {
            addCriterion("phone_no is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNoEqualTo(String value) {
            addCriterion("phone_no =", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotEqualTo(String value) {
            addCriterion("phone_no <>", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoGreaterThan(String value) {
            addCriterion("phone_no >", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoGreaterThanOrEqualTo(String value) {
            addCriterion("phone_no >=", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLessThan(String value) {
            addCriterion("phone_no <", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLessThanOrEqualTo(String value) {
            addCriterion("phone_no <=", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLike(String value) {
            addCriterion("phone_no like", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotLike(String value) {
            addCriterion("phone_no not like", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIn(List<String> values) {
            addCriterion("phone_no in", values, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotIn(List<String> values) {
            addCriterion("phone_no not in", values, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoBetween(String value1, String value2) {
            addCriterion("phone_no between", value1, value2, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotBetween(String value1, String value2) {
            addCriterion("phone_no not between", value1, value2, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNoIsNull() {
            addCriterion("mobile_phone_no is null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNoIsNotNull() {
            addCriterion("mobile_phone_no is not null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNoEqualTo(String value) {
            addCriterion("mobile_phone_no =", value, "mobilePhoneNo");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNoNotEqualTo(String value) {
            addCriterion("mobile_phone_no <>", value, "mobilePhoneNo");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNoGreaterThan(String value) {
            addCriterion("mobile_phone_no >", value, "mobilePhoneNo");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNoGreaterThanOrEqualTo(String value) {
            addCriterion("mobile_phone_no >=", value, "mobilePhoneNo");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNoLessThan(String value) {
            addCriterion("mobile_phone_no <", value, "mobilePhoneNo");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNoLessThanOrEqualTo(String value) {
            addCriterion("mobile_phone_no <=", value, "mobilePhoneNo");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNoLike(String value) {
            addCriterion("mobile_phone_no like", value, "mobilePhoneNo");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNoNotLike(String value) {
            addCriterion("mobile_phone_no not like", value, "mobilePhoneNo");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNoIn(List<String> values) {
            addCriterion("mobile_phone_no in", values, "mobilePhoneNo");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNoNotIn(List<String> values) {
            addCriterion("mobile_phone_no not in", values, "mobilePhoneNo");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNoBetween(String value1, String value2) {
            addCriterion("mobile_phone_no between", value1, value2, "mobilePhoneNo");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNoNotBetween(String value1, String value2) {
            addCriterion("mobile_phone_no not between", value1, value2, "mobilePhoneNo");
            return (Criteria) this;
        }

        public Criteria andMailAddressIsNull() {
            addCriterion("mail_address is null");
            return (Criteria) this;
        }

        public Criteria andMailAddressIsNotNull() {
            addCriterion("mail_address is not null");
            return (Criteria) this;
        }

        public Criteria andMailAddressEqualTo(String value) {
            addCriterion("mail_address =", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressNotEqualTo(String value) {
            addCriterion("mail_address <>", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressGreaterThan(String value) {
            addCriterion("mail_address >", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressGreaterThanOrEqualTo(String value) {
            addCriterion("mail_address >=", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressLessThan(String value) {
            addCriterion("mail_address <", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressLessThanOrEqualTo(String value) {
            addCriterion("mail_address <=", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressLike(String value) {
            addCriterion("mail_address like", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressNotLike(String value) {
            addCriterion("mail_address not like", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressIn(List<String> values) {
            addCriterion("mail_address in", values, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressNotIn(List<String> values) {
            addCriterion("mail_address not in", values, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressBetween(String value1, String value2) {
            addCriterion("mail_address between", value1, value2, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressNotBetween(String value1, String value2) {
            addCriterion("mail_address not between", value1, value2, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andPostNoIsNull() {
            addCriterion("post_no is null");
            return (Criteria) this;
        }

        public Criteria andPostNoIsNotNull() {
            addCriterion("post_no is not null");
            return (Criteria) this;
        }

        public Criteria andPostNoEqualTo(String value) {
            addCriterion("post_no =", value, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoNotEqualTo(String value) {
            addCriterion("post_no <>", value, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoGreaterThan(String value) {
            addCriterion("post_no >", value, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoGreaterThanOrEqualTo(String value) {
            addCriterion("post_no >=", value, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoLessThan(String value) {
            addCriterion("post_no <", value, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoLessThanOrEqualTo(String value) {
            addCriterion("post_no <=", value, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoLike(String value) {
            addCriterion("post_no like", value, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoNotLike(String value) {
            addCriterion("post_no not like", value, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoIn(List<String> values) {
            addCriterion("post_no in", values, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoNotIn(List<String> values) {
            addCriterion("post_no not in", values, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoBetween(String value1, String value2) {
            addCriterion("post_no between", value1, value2, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoNotBetween(String value1, String value2) {
            addCriterion("post_no not between", value1, value2, "postNo");
            return (Criteria) this;
        }

        public Criteria andPrefectureCdIsNull() {
            addCriterion("prefecture_cd is null");
            return (Criteria) this;
        }

        public Criteria andPrefectureCdIsNotNull() {
            addCriterion("prefecture_cd is not null");
            return (Criteria) this;
        }

        public Criteria andPrefectureCdEqualTo(String value) {
            addCriterion("prefecture_cd =", value, "prefectureCd");
            return (Criteria) this;
        }

        public Criteria andPrefectureCdNotEqualTo(String value) {
            addCriterion("prefecture_cd <>", value, "prefectureCd");
            return (Criteria) this;
        }

        public Criteria andPrefectureCdGreaterThan(String value) {
            addCriterion("prefecture_cd >", value, "prefectureCd");
            return (Criteria) this;
        }

        public Criteria andPrefectureCdGreaterThanOrEqualTo(String value) {
            addCriterion("prefecture_cd >=", value, "prefectureCd");
            return (Criteria) this;
        }

        public Criteria andPrefectureCdLessThan(String value) {
            addCriterion("prefecture_cd <", value, "prefectureCd");
            return (Criteria) this;
        }

        public Criteria andPrefectureCdLessThanOrEqualTo(String value) {
            addCriterion("prefecture_cd <=", value, "prefectureCd");
            return (Criteria) this;
        }

        public Criteria andPrefectureCdLike(String value) {
            addCriterion("prefecture_cd like", value, "prefectureCd");
            return (Criteria) this;
        }

        public Criteria andPrefectureCdNotLike(String value) {
            addCriterion("prefecture_cd not like", value, "prefectureCd");
            return (Criteria) this;
        }

        public Criteria andPrefectureCdIn(List<String> values) {
            addCriterion("prefecture_cd in", values, "prefectureCd");
            return (Criteria) this;
        }

        public Criteria andPrefectureCdNotIn(List<String> values) {
            addCriterion("prefecture_cd not in", values, "prefectureCd");
            return (Criteria) this;
        }

        public Criteria andPrefectureCdBetween(String value1, String value2) {
            addCriterion("prefecture_cd between", value1, value2, "prefectureCd");
            return (Criteria) this;
        }

        public Criteria andPrefectureCdNotBetween(String value1, String value2) {
            addCriterion("prefecture_cd not between", value1, value2, "prefectureCd");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressKanaIsNull() {
            addCriterion("address_kana is null");
            return (Criteria) this;
        }

        public Criteria andAddressKanaIsNotNull() {
            addCriterion("address_kana is not null");
            return (Criteria) this;
        }

        public Criteria andAddressKanaEqualTo(String value) {
            addCriterion("address_kana =", value, "addressKana");
            return (Criteria) this;
        }

        public Criteria andAddressKanaNotEqualTo(String value) {
            addCriterion("address_kana <>", value, "addressKana");
            return (Criteria) this;
        }

        public Criteria andAddressKanaGreaterThan(String value) {
            addCriterion("address_kana >", value, "addressKana");
            return (Criteria) this;
        }

        public Criteria andAddressKanaGreaterThanOrEqualTo(String value) {
            addCriterion("address_kana >=", value, "addressKana");
            return (Criteria) this;
        }

        public Criteria andAddressKanaLessThan(String value) {
            addCriterion("address_kana <", value, "addressKana");
            return (Criteria) this;
        }

        public Criteria andAddressKanaLessThanOrEqualTo(String value) {
            addCriterion("address_kana <=", value, "addressKana");
            return (Criteria) this;
        }

        public Criteria andAddressKanaLike(String value) {
            addCriterion("address_kana like", value, "addressKana");
            return (Criteria) this;
        }

        public Criteria andAddressKanaNotLike(String value) {
            addCriterion("address_kana not like", value, "addressKana");
            return (Criteria) this;
        }

        public Criteria andAddressKanaIn(List<String> values) {
            addCriterion("address_kana in", values, "addressKana");
            return (Criteria) this;
        }

        public Criteria andAddressKanaNotIn(List<String> values) {
            addCriterion("address_kana not in", values, "addressKana");
            return (Criteria) this;
        }

        public Criteria andAddressKanaBetween(String value1, String value2) {
            addCriterion("address_kana between", value1, value2, "addressKana");
            return (Criteria) this;
        }

        public Criteria andAddressKanaNotBetween(String value1, String value2) {
            addCriterion("address_kana not between", value1, value2, "addressKana");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(String value) {
            addCriterion("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(String value) {
            addCriterion("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(String value) {
            addCriterion("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(String value) {
            addCriterion("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(String value) {
            addCriterion("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(String value) {
            addCriterion("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLike(String value) {
            addCriterion("birthday like", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotLike(String value) {
            addCriterion("birthday not like", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<String> values) {
            addCriterion("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<String> values) {
            addCriterion("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(String value1, String value2) {
            addCriterion("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(String value1, String value2) {
            addCriterion("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBloodTypeIsNull() {
            addCriterion("blood_type is null");
            return (Criteria) this;
        }

        public Criteria andBloodTypeIsNotNull() {
            addCriterion("blood_type is not null");
            return (Criteria) this;
        }

        public Criteria andBloodTypeEqualTo(String value) {
            addCriterion("blood_type =", value, "bloodType");
            return (Criteria) this;
        }

        public Criteria andBloodTypeNotEqualTo(String value) {
            addCriterion("blood_type <>", value, "bloodType");
            return (Criteria) this;
        }

        public Criteria andBloodTypeGreaterThan(String value) {
            addCriterion("blood_type >", value, "bloodType");
            return (Criteria) this;
        }

        public Criteria andBloodTypeGreaterThanOrEqualTo(String value) {
            addCriterion("blood_type >=", value, "bloodType");
            return (Criteria) this;
        }

        public Criteria andBloodTypeLessThan(String value) {
            addCriterion("blood_type <", value, "bloodType");
            return (Criteria) this;
        }

        public Criteria andBloodTypeLessThanOrEqualTo(String value) {
            addCriterion("blood_type <=", value, "bloodType");
            return (Criteria) this;
        }

        public Criteria andBloodTypeLike(String value) {
            addCriterion("blood_type like", value, "bloodType");
            return (Criteria) this;
        }

        public Criteria andBloodTypeNotLike(String value) {
            addCriterion("blood_type not like", value, "bloodType");
            return (Criteria) this;
        }

        public Criteria andBloodTypeIn(List<String> values) {
            addCriterion("blood_type in", values, "bloodType");
            return (Criteria) this;
        }

        public Criteria andBloodTypeNotIn(List<String> values) {
            addCriterion("blood_type not in", values, "bloodType");
            return (Criteria) this;
        }

        public Criteria andBloodTypeBetween(String value1, String value2) {
            addCriterion("blood_type between", value1, value2, "bloodType");
            return (Criteria) this;
        }

        public Criteria andBloodTypeNotBetween(String value1, String value2) {
            addCriterion("blood_type not between", value1, value2, "bloodType");
            return (Criteria) this;
        }

        public Criteria andSystemThemaCdIsNull() {
            addCriterion("system_thema_cd is null");
            return (Criteria) this;
        }

        public Criteria andSystemThemaCdIsNotNull() {
            addCriterion("system_thema_cd is not null");
            return (Criteria) this;
        }

        public Criteria andSystemThemaCdEqualTo(String value) {
            addCriterion("system_thema_cd =", value, "systemThemaCd");
            return (Criteria) this;
        }

        public Criteria andSystemThemaCdNotEqualTo(String value) {
            addCriterion("system_thema_cd <>", value, "systemThemaCd");
            return (Criteria) this;
        }

        public Criteria andSystemThemaCdGreaterThan(String value) {
            addCriterion("system_thema_cd >", value, "systemThemaCd");
            return (Criteria) this;
        }

        public Criteria andSystemThemaCdGreaterThanOrEqualTo(String value) {
            addCriterion("system_thema_cd >=", value, "systemThemaCd");
            return (Criteria) this;
        }

        public Criteria andSystemThemaCdLessThan(String value) {
            addCriterion("system_thema_cd <", value, "systemThemaCd");
            return (Criteria) this;
        }

        public Criteria andSystemThemaCdLessThanOrEqualTo(String value) {
            addCriterion("system_thema_cd <=", value, "systemThemaCd");
            return (Criteria) this;
        }

        public Criteria andSystemThemaCdLike(String value) {
            addCriterion("system_thema_cd like", value, "systemThemaCd");
            return (Criteria) this;
        }

        public Criteria andSystemThemaCdNotLike(String value) {
            addCriterion("system_thema_cd not like", value, "systemThemaCd");
            return (Criteria) this;
        }

        public Criteria andSystemThemaCdIn(List<String> values) {
            addCriterion("system_thema_cd in", values, "systemThemaCd");
            return (Criteria) this;
        }

        public Criteria andSystemThemaCdNotIn(List<String> values) {
            addCriterion("system_thema_cd not in", values, "systemThemaCd");
            return (Criteria) this;
        }

        public Criteria andSystemThemaCdBetween(String value1, String value2) {
            addCriterion("system_thema_cd between", value1, value2, "systemThemaCd");
            return (Criteria) this;
        }

        public Criteria andSystemThemaCdNotBetween(String value1, String value2) {
            addCriterion("system_thema_cd not between", value1, value2, "systemThemaCd");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIsNull() {
            addCriterion("insert_user_id is null");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIsNotNull() {
            addCriterion("insert_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdEqualTo(String value) {
            addCriterion("insert_user_id =", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotEqualTo(String value) {
            addCriterion("insert_user_id <>", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdGreaterThan(String value) {
            addCriterion("insert_user_id >", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("insert_user_id >=", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLessThan(String value) {
            addCriterion("insert_user_id <", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLessThanOrEqualTo(String value) {
            addCriterion("insert_user_id <=", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLike(String value) {
            addCriterion("insert_user_id like", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotLike(String value) {
            addCriterion("insert_user_id not like", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIn(List<String> values) {
            addCriterion("insert_user_id in", values, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotIn(List<String> values) {
            addCriterion("insert_user_id not in", values, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdBetween(String value1, String value2) {
            addCriterion("insert_user_id between", value1, value2, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotBetween(String value1, String value2) {
            addCriterion("insert_user_id not between", value1, value2, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampIsNull() {
            addCriterion("insert_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampIsNotNull() {
            addCriterion("insert_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampEqualTo(Date value) {
            addCriterion("insert_timestamp =", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampNotEqualTo(Date value) {
            addCriterion("insert_timestamp <>", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampGreaterThan(Date value) {
            addCriterion("insert_timestamp >", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("insert_timestamp >=", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampLessThan(Date value) {
            addCriterion("insert_timestamp <", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampLessThanOrEqualTo(Date value) {
            addCriterion("insert_timestamp <=", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampIn(List<Date> values) {
            addCriterion("insert_timestamp in", values, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampNotIn(List<Date> values) {
            addCriterion("insert_timestamp not in", values, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampBetween(Date value1, Date value2) {
            addCriterion("insert_timestamp between", value1, value2, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampNotBetween(Date value1, Date value2) {
            addCriterion("insert_timestamp not between", value1, value2, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("update_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("update_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterion("update_timestamp =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterion("update_timestamp <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterion("update_timestamp >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("update_timestamp >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterion("update_timestamp <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("update_timestamp <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterion("update_timestamp in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterion("update_timestamp not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("update_timestamp between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("update_timestamp not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.m_user_detail
     *
     * @mbg.generated do_not_delete_during_merge Sat Nov 26 13:37:05 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.m_user_detail
     *
     * @mbg.generated Sat Nov 26 13:37:05 JST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}