package com.example.demo.model.mybatis;

public class TRoleMstMenuKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_role_mst_menu.role_cd
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    private String roleCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_role_mst_menu.mst_table_physical_nm
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    private String mstTablePhysicalNm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_role_mst_menu.role_cd
     *
     * @return the value of public.t_role_mst_menu.role_cd
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public String getRoleCd() {
        return roleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_role_mst_menu.role_cd
     *
     * @param roleCd the value for public.t_role_mst_menu.role_cd
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public void setRoleCd(String roleCd) {
        this.roleCd = roleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_role_mst_menu.mst_table_physical_nm
     *
     * @return the value of public.t_role_mst_menu.mst_table_physical_nm
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public String getMstTablePhysicalNm() {
        return mstTablePhysicalNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_role_mst_menu.mst_table_physical_nm
     *
     * @param mstTablePhysicalNm the value for public.t_role_mst_menu.mst_table_physical_nm
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    public void setMstTablePhysicalNm(String mstTablePhysicalNm) {
        this.mstTablePhysicalNm = mstTablePhysicalNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_mst_menu
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TRoleMstMenuKey other = (TRoleMstMenuKey) that;
        return (this.getRoleCd() == null ? other.getRoleCd() == null : this.getRoleCd().equals(other.getRoleCd()))
            && (this.getMstTablePhysicalNm() == null ? other.getMstTablePhysicalNm() == null : this.getMstTablePhysicalNm().equals(other.getMstTablePhysicalNm()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_mst_menu
     *
     * @mbg.generated Fri Dec 23 19:52:51 JST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleCd() == null) ? 0 : getRoleCd().hashCode());
        result = prime * result + ((getMstTablePhysicalNm() == null) ? 0 : getMstTablePhysicalNm().hashCode());
        return result;
    }
}