package com.example.demo.model.mybatis;

public class TUserRoleKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_user_role.user_id
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_user_role.role_cd
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    private String roleCd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_user_role.user_id
     *
     * @return the value of public.t_user_role.user_id
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_user_role.user_id
     *
     * @param userId the value for public.t_user_role.user_id
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_user_role.role_cd
     *
     * @return the value of public.t_user_role.role_cd
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public String getRoleCd() {
        return roleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_user_role.role_cd
     *
     * @param roleCd the value for public.t_user_role.role_cd
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    public void setRoleCd(String roleCd) {
        this.roleCd = roleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_user_role
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TUserRoleKey other = (TUserRoleKey) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getRoleCd() == null ? other.getRoleCd() == null : this.getRoleCd().equals(other.getRoleCd()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_user_role
     *
     * @mbg.generated Thu Dec 08 20:36:33 JST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getRoleCd() == null) ? 0 : getRoleCd().hashCode());
        return result;
    }
}