# DB管理
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

# メッセージリソース管理
spring.messages.basename=messages
spring.messages.cache-duration=-1
spring.messages.encoding=UTF-8

# mybatisログ出力設定
logging.level.org.springframework=WARN
logging.level.com.example.demo.mapper=DEBUG

# ログファイル出力設定
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.file.path=C:/eclipse/pleiades/workspace2/log/
